---
name: Security Scan with ASH Action

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  pull-requests: write
  actions: read

jobs:
  security-scan:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          - path: './frontend'
            scanners: 'semgrep,npm-audit'
            category: 'frontend'
          - path: './backend'
            scanners: 'bandit,semgrep'
            category: 'backend'
          - path: './infrastructure'
            scanners: 'checkov,cfn-nag'
            category: 'infrastructure'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run ASH Security Scan - ${{ matrix.target.category }}
        uses: rickardl/automated-security-helper-action@v1.0.4
        with:
          source-directory: ${{ matrix.target.path }}
          scanners: ${{ matrix.target.scanners }}
          sarif-category: ${{ matrix.target.category }}
          fail-on-findings: false
          severity-threshold: 'medium'
          upload-sarif: true
          pr-comment: true
          pr-comment-format: 'sarif'
          parallel-execution: true
          enable-caching: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

  comprehensive-scan:
    runs-on: ubuntu-latest
    needs: security-scan
    if: always()

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Comprehensive Security Scan
        uses: rickardl/automated-security-helper-action@v1.0.4
        with:
          source-directory: '.'
          output-format: 'both'
          fail-on-findings: false
          severity-threshold: 'low'
          upload-sarif: true
          sarif-category: 'comprehensive'
          pr-comment: true
          pr-comment-format: 'sarif'
          parallel-execution: true
          enable-caching: true
          upload-artifacts: true
          artifact-retention-days: 30
          github-token: ${{ secrets.GITHUB_TOKEN }}
