---
name: Security Scan with ASH Action

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      pull-requests: write

    strategy:
      matrix:
        target:
          - path: './frontend'
            scanners: 'semgrep,npm-audit'
            category: 'frontend'
          - path: './backend'
            scanners: 'bandit,semgrep'
            category: 'backend'
          - path: './infrastructure'
            scanners: 'checkov,cfn-nag'
            category: 'infrastructure'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run ASH Security Scan - ${{ matrix.target.category }}
        uses: rickardl/automated-security-helper-action@v2
        with:
          source-directory: ${{ matrix.target.path }}
          scanners: ${{ matrix.target.scanners }}
          sarif-category: ${{ matrix.target.category }}
          fail-on-findings: false
          severity-threshold: 'medium'
          upload-sarif: true
          pr-comment: true
          pr-comment-format: 'sarif'
          parallel-execution: true
          enable-caching: true

  comprehensive-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Comprehensive Security Scan
        uses: rickardl/automated-security-helper-action@v2
        with:
          source-directory: '.'
          output-format: 'both'
          fail-on-findings: false
          severity-threshold: 'low'
          upload-sarif: true
          sarif-category: 'comprehensive'
          pr-comment: true
          pr-comment-format: 'sarif'
          parallel-execution: true
          enable-caching: true
          upload-artifacts: true
          artifact-retention-days: 30
